Repository cloudposse-github-actions/test-action, pull requests merged in 2024-05, with the labels that each got.

#120 Use GitHub Action Workflows from `cloudposse/.github` Repo
  .github/workflows/release.yml
Labels: auto-update, no-release, migration

#124 Test 2
  action.yml
Labels: major

#125 Test 3
  action.yml
Labels: major

#127 Test 4
  action.yml
Labels: major

#129 Test 6
  action.yml
Labels: no-release

#131 Test 7
  action.yml
Labels: no-release

#135 Test 13
  action.yml
Labels: no-release

#136 Test 14
  action.yml
Labels: no-release

#139 Use GitHub Action Workflows from `cloudposse/.github` Repo
  .github/workflows/branch.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release.yml
Labels: auto-update, no-release, migration

#141 Update release workflow
  .github/workflows/release.yml
Labels: auto-update, no-release, migration
